/*
 * Client Hub Open Project
 * Copyright (C) 2025 Client Hub Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// BONUS - Temas Complementares e Especiais
export const bonusThemes = {
    blue_orange: {
        name: "Azul e Laranja",
        light: {
            buttonPrimary: "#2563eb",
            buttonSecondary: "#ea580c",
            bgPage: "#eff6ff",
            bgCard: "#ffffff",
            textPrimary: "#1e40af",
            textSecondary: "#9a3412",
            borderDefault: "#93c5fd",
            textNav: "#ffffff",
            bgNavbar: "#2563eb",
            textTitle: "#1e40af",
            textNavActive: "#eff6ff",
        },
        dark: {
            buttonPrimary: "#3b82f6",
            buttonSecondary: "#f97316",
            bgPage: "#0f172a",
            bgCard: "#1e293b",
            textPrimary: "#dbeafe",
            textSecondary: "#fdba74",
            borderDefault: "#1d4ed8",
            textNav: "#ffffff",
            bgNavbar: "#0f172a",
            textTitle: "#3b82f6",
            textNavActive: "#dbeafe",
        },
    },
    red_green: {
        name: "Vermelho e Verde",
        light: {
            buttonPrimary: "#dc2626",
            buttonSecondary: "#16a34a",
            bgPage: "#fef2f2",
            bgCard: "#ffffff",
            textPrimary: "#991b1b",
            textSecondary: "#166534",
            borderDefault: "#fecaca",
            textNav: "#ffffff",
            bgNavbar: "#dc2626",
            textTitle: "#991b1b",
            textNavActive: "#fef2f2",
        },
        dark: {
            buttonPrimary: "#ef4444",
            buttonSecondary: "#22c55e",
            bgPage: "#1f0505",
            bgCard: "#2d0f0f",
            textPrimary: "#fef2f2",
            textSecondary: "#86efac",
            borderDefault: "#b91c1c",
            textNav: "#ffffff",
            bgNavbar: "#450a0a",
            textTitle: "#ef4444",
            textNavActive: "#fef2f2",
        },
    },
    purple_yellow: {
        name: "Roxo e Amarelo",
        light: {
            buttonPrimary: "#7c3aed",
            buttonSecondary: "#ca8a04",
            bgPage: "#faf5ff",
            bgCard: "#ffffff",
            textPrimary: "#5b21b6",
            textSecondary: "#854d0e",
            borderDefault: "#c4b5fd",
            textNav: "#ffffff",
            bgNavbar: "#7c3aed",
            textTitle: "#5b21b6",
            textNavActive: "#faf5ff",
        },
        dark: {
            buttonPrimary: "#a78bfa",
            buttonSecondary: "#facc15",
            bgPage: "#1a1025",
            bgCard: "#2d1640",
            textPrimary: "#ede9fe",
            textSecondary: "#fde047",
            borderDefault: "#6d28d9",
            textNav: "#ffffff",
            bgNavbar: "#1a1025",
            textTitle: "#a78bfa",
            textNavActive: "#ede9fe",
        },
    },
    neon: {
        name: "Cyberpunk",
        light: {
            buttonPrimary: "#FF003C",
            buttonSecondary: "#FCEE0A",
            bgPage: "#131313",
            bgCard: "#1a1a1a",
            textPrimary: "#00F0FF",
            textSecondary: "#FCEE0A",
            borderDefault: "#00F0FF",
            textNav: "#00F0FF",
            bgNavbar: "#131313",
            textTitle: "#FF003C",
            textNavActive: "#FCEE0A",
        },
        dark: {
            buttonPrimary: "#FF003C",
            buttonSecondary: "#FCEE0A",
            bgPage: "#131313",
            bgCard: "#1a1a1a",
            textPrimary: "#00F0FF",
            textSecondary: "#FCEE0A",
            borderDefault: "#00F0FF",
            textNav: "#00F0FF",
            bgNavbar: "#131313",
            textTitle: "#FF003C",
            textNavActive: "#FCEE0A",
        },
    },
    pastel: {
        name: "Pastel Clássico",
        light: {
            buttonPrimary: "#fbbf24",
            buttonSecondary: "#f472b6",
            bgPage: "#fefce8",
            bgCard: "#ffffff",
            textPrimary: "#333333",
            textSecondary: "#666666",
            borderDefault: "#fde68a",
            textNav: "#1a1a1a",
            bgNavbar: "#fcd34d",
            textTitle: "#92400e",
            textNavActive: "#fefce8",
        },
        dark: {
            buttonPrimary: "#fcd34d",
            buttonSecondary: "#f9a8d4",
            bgPage: "#1f1a0f",
            bgCard: "#3d3019",
            textPrimary: "#f7fafc",
            textSecondary: "#a0aec0",
            borderDefault: "#92400e",
            textNav: "#ffffff",
            bgNavbar: "#1f1a0f",
            textTitle: "#fcd34d",
            textNavActive: "#f7fafc",
        },
    },
    pastel_ocean: {
        name: "Pastel Oceano",
        light: {
            buttonPrimary: "#67e8f9",
            buttonSecondary: "#a5b4fc",
            bgPage: "#ecfeff",
            bgCard: "#ffffff",
            textPrimary: "#155e75",
            textSecondary: "#3730a3",
            borderDefault: "#a5f3fc",
            textNav: "#1a1a1a",
            bgNavbar: "#22d3ee",
            textTitle: "#0e7490",
            textNavActive: "#ecfeff",
        },
        dark: {
            buttonPrimary: "#22d3ee",
            buttonSecondary: "#818cf8",
            bgPage: "#083344",
            bgCard: "#0c4a6e",
            textPrimary: "#cffafe",
            textSecondary: "#c7d2fe",
            borderDefault: "#0891b2",
            textNav: "#ffffff",
            bgNavbar: "#083344",
            textTitle: "#22d3ee",
            textNavActive: "#cffafe",
        },
    },
    matrix: {
        name: "Matrix",
        light: {
            buttonPrimary: "#22c55e",
            buttonSecondary: "#00ff00",
            bgPage: "#f0fdf4",
            bgCard: "#ffffff",
            textPrimary: "#14532d",
            textSecondary: "#166534",
            borderDefault: "#4ade80",
            textNav: "#000000",
            bgNavbar: "#dcfce7",
            textTitle: "#22c55e",
            textNavActive: "#f0fdf4",
        },
        dark: {
            buttonPrimary: "#00ff00",
            buttonSecondary: "#22c55e",
            bgPage: "#000a00",
            bgCard: "#001a00",
            textPrimary: "#00ff00",
            textSecondary: "#4ade80",
            borderDefault: "#166534",
            textNav: "#000000",
            bgNavbar: "#000800",
            textTitle: "#00ff00",
            textNavActive: "#000000",
        },
    },
};
